[package]
name = "Mazeir"
authors = ["Scalt"]
version = "0.1.0"
edition = "2021"
license-file = "./LICENSE"
keywords = ['maze', 'depth-first']

[lib]
name = "mazeir"
path = "src/lib.rs"

[[bin]]
name = "mazeir"
path = "src/cli.rs"

[dependencies]
rand = "0.8.5"
image = "0.24.0"
